### ISSUE TITLE
Publish APK?

### ISSUE THREAD

**Issue by IzzySoft** [alabeduarte/mypodcasts-android#20]
Any plans to make an `.apk` available here, so non-devs could give the app a try as well?

**Comment by alabeduarte** [comment]
Hi @IzzySoft 

I have some issues to tackle before publish the APK which are #12 (ability to create a playlist), #13 (user authentication) and #14 (feed subscription, since nowadays a few feeds that I choose are hardcoded).

If you wish to try out, please let me know your email so then I can send the latest version of the apk through the [beta testing provider](https://testfairy.com/) that I use. Once you receive the email with the apk, from time to time I can send updated versions. How does that sounds to you?

Thanks for asking and showing interest.

Best regards.

**Comment by IzzySoft** [comment]
Thanks for the fast response, @alabeduarte ! I was not asking for myself. I just walk Github frequently to check for promising apps, and try to encourage their devs and help "promoting" those apps e.g. by placing them into [my repo](https://android.izzysoft.de/repo), where folks then can obtain them and keep them updated using the regular F-Droid client.

So if you're interested, and have an `.apk` available here at Github (preferably in the `releases/`  section, see [Creating Releases](https://help.github.com/articles/creating-releases/) – but "just somewhere in the repo" would work as well), just let me know and I'll take care for the rest.

**Comment by IzzySoft** [comment]
Thanks! Just wondering: all the packages are suffixed "unsigned". Shouldn't they be "signed" for end-users to install?

**Comment by alabeduarte** [comment]
Hi @IzzySoft 

I kept as an unsigned suffix to make explicit that this is under development. Besides, it's not available on Play Store. When I publish the apk to Play Store, then I'll have to sign it. Does it make sense?

**Comment by IzzySoft** [comment]
Somehow, yes :smile: So you especially don't want it spread too far in its current state (I was thinking of e.g. putting it into [my F-Droid compatible repo](https://android.izzysoft.de/repo) for easy installs/updates). I take it you'd consider that "premature"?

**Comment by alabeduarte** [comment]
Hi @IzzySoft

Yeah, I would say so.
At this point there is a lot of missing features despite the app is able to stream audio.

Do you have any suggestion?

Cheers

**Comment by IzzySoft** [comment]
Of course it's your decision – and there are multiple possibilities:

* keeping it as it is (i.e. for interested testers, provide the APK solely via Github)
* additionally to the former, I could already take it into my repo to make it easier for the testers
* again additionally, you could have it on Playstore in the "test channel" (i.e. interested folks would have to explicitly "register" to that somehow – I've never tried that)
* alternatively to the previous, you could deploy it to Playstore already as "unpublished" (so it's visible there but quite clear it's not "production ready" yet; there is such a funny state, as I've seen it a couple of times).

Of course, other "mixtures" are possible as well (e.g. Github plus Play-test-channel). Whatever suits you best. If at some point you want me taking it into my repo, just let me know.

**Comment by alabeduarte** [comment]
Thank you @IzzySoft

**Comment by IzzySoft** [comment]
Anytime! You let me know then?

**Comment by alabeduarte** [comment]
Sure @IzzySoft, go for it!

**Comment by IzzySoft** [comment]
Well, can't – the latest package (v0.1.7-34) seems still to be unsigned:

    CRITICAL: Failed to get apk signature

Another thing when it comes to releases for the repo:

    package: name='com.mypodcasts' versionCode='1' versionName='0.1.7' platformBuildVersionName='6.0-2166767'

Please remember increasing `versionCode` with each release. That's how updates are recognized internally. F-Droid repo cannot deal with multiple copies the same package if they also have identical `versionCode` :wink:

**Comment by alabeduarte** [comment]
Thanks @IzzySoft 

I'll open an issue specifically for this, ok?

**Comment by IzzySoft** [comment]
Whatever is best for you to keep it in mind :innocent: What's left is the signing: fdroid-server doesn't accept unsigned APKs either.

**Comment by alabeduarte** [comment]
👍 got it!

**Comment by IzzySoft** [comment]
:+1: When there's a signed package attached, please let me know and I try again :wink:
